
image: python:3.8

options:
  docker: true

pipelines:
  branches:
    production-main:
      - step:
          name: Docker Build
          deployment: production
          caches:
            - pip
          script:
            - export IMAGE_NAME=bascogroup/botty.py
            - export BUILD_IMAGE=$IMAGE_NAME:$BITBUCKET_COMMIT
            - export NEW_IMAGE=$IMAGE_NAME:latest 
            - docker build -t $NEW_IMAGE .
            - docker login --username $DOCKER_USER --password $DOCKER_PASS
            - docker push $NEW_IMAGE
    testing-main:
      - step:
          name: Docker Build
          deployment: test
          caches:
            - pip
          script:
            - export IMAGE_NAME=bascogroup/botty-test.py
            - export BUILD_IMAGE=$IMAGE_NAME:$BITBUCKET_COMMIT
            - export NEW_IMAGE=$IMAGE_NAME:latest            
            - docker build -t $NEW_IMAGE .
            - docker login --username $DOCKER_USER --password $DOCKER_PASS
            - docker push $NEW_IMAGE
